### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by estianross** [stefanfoulis/django-phonenumber-field#221] opened 2018-06-27 11:02 UTC
This package has no useful documentation, this makes it slow to figure out and implement anything with it. Please can some actual proper documentation be provided? Simple usage examples provided are often inadequate for understanding the package.

**Comment by reshimahendra** [comment] 2018-07-04 16:29
Agree, I spent hours already tried to figured out how to add the widget to the phone input on my ModelForm class without a luck..

**Comment by striderr** [comment] 2018-07-22 08:17
Please provide good documentation, I will start.

models.py
```
`from phonenumber_field.modelfields import PhoneNumberField`

class UserProfile(models.Model):
...
cell_phone = PhoneNumberField(blank=True)
```
```
```

Import widgets
forms.py
`from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget, PhoneNumberPrefixWidget`

Use your widget with forms
forms.py
```
class UserProfileForm(forms.ModelForm):
...
cell_phone = PhoneNumberField(widget=PhoneNumberPrefixWidget(attrs={'class': 'form-control'}))
```

I haven't got to the point of being able to see this new field/data inside the admin interface though.

**Comment by KrunchMuffin** [comment] 2018-12-03 19:04
ok, so I am trying to follow this "doc" but I am going to jump off a bridge. Can't figure out how this is configured for non-admin implementation. I am also using crispy. 
With crispy I get
> 'PhoneNumberField' object has no attribute 'is_hidden'

when I take out `as_crispy_field` I get
> 'PhoneNumberField' object has no attribute 'use_required_attribute'

**Comment by stefanfoulis** [comment] 2018-12-07 15:17
@KrunchMuffin I totally agree we need better docs. I'm not familiar with crispy forms. One thing that might have happened, is a mixup between the form-field and the model-field (just guessing). Do you have some example code so we could reproduce the error?

**Comment by jdufresne** [comment] 2019-04-19 14:30
:+1: To more docs.

Duplicate of #152

**Closed by jdufresne** 2019-04-19 14:30 UTC

**Comment by shawnngtq** [comment] 2021-03-13 06:41
@KrunchMuffin , it has been 2+ years, so in the end how do you use it with django crispy form? 😁
