### ISSUE TITLE
Django Rest Framework Support

### ISSUE THREAD

**Issue by NBajanca** [stefanfoulis/django-phonenumber-field#156] opened 2017-01-31 14:58 UTC
It would be interesting to have also a [serializer field](http://www.django-rest-framework.org/api-guide/fields/).

**Comment by hairychris** [comment] 2017-02-06 07:58
Duplicate of https://github.com/stefanfoulis/django-phonenumber-field/issues/72 which contains a work around but no permanent solution. I came here looking for DRF support also.

**Comment by hairychris** [comment] 2017-02-06 07:59
There is also an example here https://github.com/stefanfoulis/django-phonenumber-field/pull/150

**Comment by tredzko** [comment] 2017-06-29 14:09
With #150 merged, this issue should be closed.

**Closed** 2017-06-29 17:54 UTC
