### ISSUE TITLE
German Number with format +491765770313

### ISSUE THREAD

**Issue by AbdurRehman91** [stefanfoulis/django-phonenumber-field#167] opened 2017-04-07 11:38 UTC
hi,i am using this number in my django application.When user signsUp at first,it basically validates it and works fine.But when it is being used for some use case,that 's where django-phonenumber filed gives error

**Comment by kevin-brown** [comment] 2017-04-07 18:07
This is an issue in the upstream libphonenumber, probably stemming from a default country code not being set.

https://libphonenumber.appspot.com/phonenumberparser?number=491765770313

**Comment by AbdurRehman91** [comment] 2017-04-07 18:53
sorry.but can you elaborate the reply more specifically
thanks

**Comment by AbdurRehman91** [comment] 2017-04-09 10:40
hi kevin..what can be the possible solution for this according to you?

**Comment by amateja** [comment] 2017-04-10 04:28
Actually, my friend, your solution is here #166. Let us know if you have more issues.

**Comment by jdufresne** [comment] 2019-04-19 14:14
The number validates for me with an updated version of python-phonenumbers.

Closing as it looks like this is an upstream issue and possibly fixed there as well. If you believe this is still an issue with the django-phonenumber-field project, please provide additional details with an easy to reproduce test case.

**Closed by jdufresne** 2019-04-19 14:14 UTC
