### ISSUE TITLE
Not able to save phone number with 83.. series using django phonenumber field

### ISSUE THREAD

**Issue by sunnychaudhari** [stefanfoulis/django-phonenumber-field#166] opened 2017-03-17 10:55 UTC
I'm trying to store phone number +918369232477 using django phone number field, as I have installed this in my django project but this number is not getting stored. Currently this is the new series numbers that reliance jio providers in India have launched with. Giving me error as its not valid phone number. Apart from this all other 10 digit numbers are getting saved such as +919899999999 , +917699889898, ...etc

I think this library doesn't support this series of phone numbers. Please help me in this issue.

**Comment by amateja** [comment] 2017-03-17 10:59
Actually this project is only a Django wrapper over https://github.com/daviddrysdale/python-phonenumbers and your problem should be reported there. Sorry.

**Comment by sunnychaudhari** [comment] 2017-03-17 11:05
Thanks

**Comment by sunnychaudhari** [comment] 2017-03-18 05:47
Just see this I think its now updated as per my requirement. 
https://github.com/googlei18n/libphonenumber/issues/1641

Since django-phonenumber-field is wrapper, will it take this update automatically ? Let me know.

**Comment by tredzko** [comment] 2017-03-20 15:10
@sunnychaudhari That issue is on the google-run phone number library. This package wraps around [python-phonenumber](https://github.com/daviddrysdale/python-phonenumbers) ( per @amateja ), which is a python port of that library. It currently looks as though the maintainer is [in the process of prepping a release for v8.3.3](https://github.com/daviddrysdale/python-phonenumbers/commit/dc1fd683f941fb289480fd31527652e5e4beee96), which is the most recent release of the google library. It may not be fixed right this moment, but if you create an issue over there I'm sure they can respond and track the problem to ensure it's fixed for their v8.3.3 port.

**Comment by BillBrower** [comment] 2018-09-29 22:32
I'm getting around this by defining custom validation methods, that return an E164 formatted phone number, on my serializers for all of my phone number fields.

```python
import phonenumbers

def validate_phone_number(value, field_name):
    if not value:
        return value

    parsed = phonenumbers.parse(value, 'US')
    if not phonenumbers.is_possible_number(parsed):
        raise serializers.ValidationError("{} is not a valid US phone number.".format(field_name))
    return phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.E164)
```
In my case, I only need to store US phone numbers but you should be able to change `US` to any other [supported country code](https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/phonenumbers/data/__init__.py) OR try to parse the number for a series of country codes/regions if you need to accept numbers in multiple formats.

**Comment by jdufresne** [comment] 2019-04-19 14:12
Closing as it looks like this is an upstream issue and possibly fixed there as well. If you believe this is still an issue with the django-phonenumber-field project, please provide additional details with an easy to reproduce test case.

**Closed by jdufresne** 2019-04-19 14:12 UTC
